
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-maven
  annotations:
    backstage.io/kubernetes-id: springboot-maven
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: benwilcock-org/springboot-maven
spec:
  type: api
  system: system:default/parasol
  lifecycle: production
  owner: user:default/benwilcock
